memory_manager.o : memory_manager.cpp
	g++ -c -g memory_manager.cpp

random_fit_allocation.o : random_fit_allocation.cpp	
	g++ -c -g random_fit_allocation.cpp

best_fit_allocation.o : best_fit_allocation.cpp
	g++ -c -g best_fit_allocation.cpp

worst_fit_allocation.o : worst_fit_allocation.cpp
	g++ -c -g worst_fit_allocation.cpp

first_fit_allocation.o: first_fit_allocation.cpp
	g++ -c -g first_fit_allocation.cpp

memory_block.o : memory_block.cpp
	g++ -c -g memory_block.cpp

memory_allocation.o : memory_allocation.cpp
	g++ -c -g memory_allocation.cpp

test_mem.o : test_mem.cpp
	g++ -c -g test_mem.cpp

test_mem : test_mem.o memory_manager.o random_fit_allocation.o best_fit_allocation.o worst_fit_allocation.o first_fit_allocation.o memory_block.o memory_allocation.o
	g++ -o test_mem test_mem.o memory_manager.o random_fit_allocation.o best_fit_allocation.o worst_fit_allocation.o first_fit_allocation.o memory_block.o memory_allocation.o