#! /bin/bash
echo "what is the number?"
read num

echo "checking the following ports: "
echo "checking "$num"0"$num"0"
netstat -pln | grep $num"0"$num"0"
echo "checking "$num"443"
netstat -pln | grep $num"443"
echo "checking "$num"009"
netstat -pln | grep $num"009"
echo "checking "$num"3873"
netstat -pln | grep $num"3873"
echo "checking "$num"093"
netstat -pln | grep $num"093"
echo "checking "$num"083"
netstat -pln | grep $num"083"
echo "checking "$num"099"
netstat -pln | grep $num"099"
echo "checking "$num"098"
netstat -pln | grep $num"098"
echo "checking "$num"444"
netstat -pln | grep $num"444"
echo "checking "$num"445"
netstat -pln | grep $num"445"
echo "checking "$num"446"
netstat -pln | grep $num"446"