// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.261
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestProject1.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("FizzBuzz Contains")]
    public partial class FizzBuzzContainsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Contains.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "FizzBuzz Contains", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("fizz prints correctly for contains a 3")]
        public virtual void FizzPrintsCorrectlyForContainsA3()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("fizz prints correctly for contains a 3", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.Given("I have 100 integers");
#line 5
 testRunner.When("I fizzbuzz");
#line 6
 testRunner.And("get all numbers containing a 3");
#line 7
 testRunner.But("not divisible by 5");
#line 8
 testRunner.And("not contains a 5");
#line 9
 testRunner.Then("each should be fizz");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("fizz prints correctly for contains a 5")]
        public virtual void FizzPrintsCorrectlyForContainsA5()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("fizz prints correctly for contains a 5", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("I have 100 integers");
#line 13
 testRunner.When("I fizzbuzz");
#line 14
 testRunner.And("get all numbers containing a 5");
#line 15
 testRunner.But("not divisible by 3");
#line 16
 testRunner.And("not contains a 3");
#line 17
 testRunner.Then("each should be buzz");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("fizzbuzz prints correctly for contains a 3 and 5")]
        public virtual void FizzbuzzPrintsCorrectlyForContainsA3And5()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("fizzbuzz prints correctly for contains a 3 and 5", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
 testRunner.Given("I have 100 integers");
#line 21
 testRunner.When("I fizzbuzz");
#line 22
 testRunner.And("get all numbers containing a 3");
#line 23
 testRunner.And("get all numbers containing a 5");
#line 24
 testRunner.But("not divisible by 3");
#line 25
 testRunner.And("not contains a 3");
#line 26
 testRunner.Then("each should be buzz");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("fizzbuzz prints correctly for contains a 3 and divisible by 5")]
        public virtual void FizzbuzzPrintsCorrectlyForContainsA3AndDivisibleBy5()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("fizzbuzz prints correctly for contains a 3 and divisible by 5", ((string[])(null)));
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given("I have 100 integers");
#line 31
 testRunner.When("I fizzbuzz");
#line 32
 testRunner.And("get all numbers containing a 3");
#line 33
 testRunner.And("get all numbers divisible by 5");
#line 34
 testRunner.Then("each should be fizzbuzz");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
