#include <iostream>
#include <string>
   int main(){
   		string temp("1000");
   		

      unsigned int itest=0;
      /*
   	float ftest=0;
      double dtest=0;
      cout<<ftest<<endl;
         cout<<dtest<<endl;
   	   ftest++;
         dtest++;
   	
      	
   	char zero='0';
      cout<<"A goolgle: \n1";
      for (int i=0; i<100; i++){
         for (int j=0; j<i*10; j++){
            cout<<"0";
            itest++;
         }
         temp[i]=zero;	
      
      }*/
   	itest=atoi(c_str(temp));
      cout<<"temp: "<<temp<<endl;
   	cout <<"itest: "<<itest; 
      return 0;
   }