/*
DROP TABLE JunkDB..JCP_URL_08082013

CREATE TABLE JunkDB..JCP_URL_08082013 (
	CSKID INT,
	URL NVARCHAR(MAX),-- COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	Processed BIT DEFAULT (0),
	PRIMARY KEY CLUSTERED (Processed,CSKID)
)
SELECT COUNT(1) FROM JunkDB..JCP_URL_08082013

*/

DECLARE @BSize INT = 50000,
	@TimeOut VARCHAR(30) = '00:20:00.000'

CREATE TABLE #CSK (
	CSKID INT,
	URL NVARCHAR(MAX),
	PRIMARY KEY CLUSTERED (CSKID)
)


WHILE EXISTS (SELECT TOP 1 1 FROM JunkDB..JCP_URL_08082013 WHERE Processed = 0)
BEGIN

	TRUNCATE TABLE #CSK
	
	INSERT INTO #CSK (CSKID, URL)
	SELECT TOP (@BSize) CSKID, URL
	FROM JunkDB..JCP_URL_08082013
	WHERE Processed = 0

	UPDATE csk
	SET RedirectURL = c.URL,
		UpdateDate = GETUTCDATE()
	FROM Searchignite..CSKeywords csk
	JOIN #CSK c ON c.CSKID = csk.CSKID

	UPDATE j
	SET Processed = 1
	FROM JunkDB..JCP_URL_08082013 j
	JOIN #CSK c ON c.CSKID = j.CSKID
	WHERE Processed = 0

	
	RAISERROR ('Batch Complete', 0, 1) WITH Nowait

	WAITFOR DELAY @TimeOUt

END